# Generated by Django 3.1.2 on 2020-10-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='Mô tả')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('composed_in', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Mô tả')),
                ('thumbnail', models.FileField(blank=True, upload_to='thumbnail')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='webtruyenvui.story')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, upload_to='chapter', verbose_name='Hình ảnh')),
                ('content', models.TextField(blank=True, max_length=2500, verbose_name='Nội dung')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='webtruyenvui.story')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
